app_name : e-commerce
key :
  access_token: "123"
  refresh_token: "123"
server:
  host : 0.0.0.0
  port: 8080
  path : /api
amqp:
  url : amqp://guest:guest@localhost:5672/
db:
  host : localhost
  port : "27018"
  user : username
  password : password
  name : e-commerce
upload:
  upload_path : /frontend_project/public
  server_path : /frontend_project/public