services:
  mongodb:
    image: mongo:7.0
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27018:27017"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INIT_DB}

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

volumes:
  mongodb-data:
  redis-data:
  rabbitmq-data: