name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

env:
  VERSION: ${{ github.sha }}
  ARTIFACT_REGISTRY: asia-southeast1-docker.pkg.dev/learn-441406/ecom-back
  REGISTRY_IMAGE: ecom-back

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
      
      - name: Build and Push Image
        run: make cicd
      
      - name: Deploy to VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << EOF
          docker pull ${{ env.ARTIFACT_REGISTRY }}/${{ env.REGISTRY_IMAGE }}:$(git rev-parse --short HEAD)
          docker stop ${{ env.REGISTRY_IMAGE }} || true
          docker rm ${{ env.REGISTRY_IMAGE }} || true
          docker run -d \
            --name ${{ env.REGISTRY_IMAGE }} \
            --restart always \
            -p 8080:8080 \
            ${{ env.ARTIFACT_REGISTRY }}/${{ env.REGISTRY_IMAGE }}:$(git rev-parse --short HEAD)
          EOF