name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

env:
  VERSION: ${{ github.sha }}
  ARTIFACT_REGISTRY: asia-southeast1-docker.pkg.dev/learn-441406/ecom-back
  REGISTRY_IMAGE: ecom-back

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}
      
      - name: Build and Push Image
        run: make cicd
      
      - name: Update Docker Compose Version and Restart
        run: |
          # Get short SHA for version tag
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Use sed to update the back service version in docker-compose.yml
          sed -i "s|asia-southeast1-docker.pkg.dev/learn-441406/ecom-back/ecom-back:[^ ]*|asia-southeast1-docker.pkg.dev/learn-441406/ecom-back/ecom-back:${SHORT_SHA}|" docker-compose.yml
          
          # Restart only the back service
          docker compose up -d 